### ISSUE TITLE
basic question how to copy out an Excel file

### ISSUE THREAD

**Issue by gitdlam** [koltyakov/gosip-sandbox#2]
Thanks for the help.
Apologies in advance if this is too basic. Quite new to sharepoint and interested to do one specific thing.

How can i copy out an Excel file?  Would it be just a matter of finding out the URL and doing a standard http request?

**Comment by koltyakov** [comment]
Hi @gitdlam,

Not sure I understood what exactly you're trying to achieve, copy a file in SharePoint to another location or download. 

There are APIs for both cases. Have you been through the [documentation article](https://go.spflow.com/samples/documents#downloading-files)? It contains basic operations with documents.

CopyTo can be used this way:

```golang
if _, err := web.GetFile(newFolderURI+"/File_5.txt").
  CopyTo(newFolderURI+"/File_5_copyed.txt", true); err != nil {
  fmt.Println(err)
}
```

**Comment by gitdlam** [comment]
Thanks heaps.  The download snippet is exactly what i needed.
