### ISSUE TITLE
Issue with gosip / Query API

### ISSUE THREAD

**Issue by pitw** [koltyakov/gosip-sandbox#3]
I'm trying to query an API of a project (../api/data/v8.2/...) built with an older version of Dynamics CRM.
Just need to get the client / cookie which should work with your library.

**On Login Mask it redirects me to:**
`https://xxx.com/adfs/ls/?wa=wsignin1.0&wtrealm=https://xxx.com/&wctx=rm=1&id=c70fc88e-1ff7-41f9-968b-f7c3ad07e788&ru=https%3a%2f%xxx.com%2fmain.aspx&crmorgid=ce89b8e6-b3bd-e911-90f4-00155d871600&wct=2021-04-17T12:25:09Z&wauth=urn:oasis:names:tc:SAML:1.0:am:password`

**Login with:**
Username: mydomain\m.test
Passwort: 1234

**After login:**
Redirects me to `https://auth-crm03.xxx.com/`

If I'm checking cookies (after login) I got this:
![image](https://user-images.githubusercontent.com/5676857/115113972-2da62380-9f8d-11eb-8cd3-cce30bf62254.png)

My test code for login is this:

`func main() {
	auth := &strategy.AuthCnfg{SiteURL: "https://xxx.com/api/data/v8.2",
		Domain:       "mydomain",
		Username:     "m.test",
		Password:     "1234",
		RelyingParty: "urn:oasis",
		AdfsURL:      "https://xxx.com",
		AdfsCookie:   "FedAuth"}

	sp := api.NewHTTPClient(&gosip.SPClient{AuthCnfg: auth})

	endpoint := auth.GetSiteURL() + "/?$select=Title"
	data, err := sp.Get(endpoint, nil)
	if err != nil {
		log.Fatalf("%v\n", err)
	}
}`

Then I either get:
` unable to request api: ID3242: The security token could not be authenticated or authorized.`

or 

` unable to request api: XML syntax error on line 167: invalid character entity & (no semicolon)`

(Depending if I use RelyingParty config or not...)

What I'm doing wrong ? Maybe you could give me a hint where I have to look or what I'm doing wrong...

**Comment by koltyakov** [comment]
Hi @pitw,

The library is for SharePoint, it is not supposed to work with Dynamics.

**Comment by koltyakov** [comment]
Is it a cloud version of Dynamics by the way?

If so, I'd suggest taking a look at AAD auth

- https://github.com/koltyakov/gosip-sandbox/blob/master/strategies/azurecert/azurecert.go and 
- https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization 

and getting Bearer injecting into a custom HTTP client.

Gosip has lots of SharePoint specific behaviours, even if it technically could consume an API from within Dynamics, I'm not sure how stable it would be on edge cases.

I just not familiar with Dynamics REST API to predict.

For ADFS auth flow, it's likely the packages are different.

**Comment by pitw** [comment]
No - its an on premise installation, hosted by a private hosting company with an own AD.
Its an ADFS auth flow without any Azure connection. 
Technically I just need the cookie / client - then I could do the queries by myselve (do login -> save cookies in cookie jar...)

My "feeling" is that the first step (=ADFS auth) is the same like in your library. But I'm not quite sure that my parameters are correct. 

- **AdfsCookie**: I made a screen above from cookies in logged in state. Is that similar to Sharepoint or completly different ?
- **RelyingParty**: I catched the query "...&wauth=urn:oasis:names:tc:SAML:1.0:am:password" during login process. Is that similar to Sharepoint ?  Could I just input urn:oasis ?

**Comment by pitw** [comment]
You're right.
In General the Auth Flow is same but the "RequestSecurityTokenResponse", the Cookies and the Endpoints are different...
(Private Hoster also customized a lot of stuff like Auth URL, etc...)
I have now a hacky solution but its works ;)
