### ISSUE TITLE
spproxy enable CORS

### ISSUE THREAD

**Issue by tarundhillon** [koltyakov/gosip-sandbox#4]
Hi Andrew 

Great effort on another excellent library. 

The proxy & the auth works fine and I am able access the site through the browser localhost:9090. When I am trying to route the rest requests from my WebApp through to the proxy I am facing CORS error

```Access to fetch at 'http://localhost:9090/_api/web' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.```

In sp-proxy/main.go I tried to add the headers manually 
```
req.Header.Add("Access-Control-Allow-Origin", "*")
req.Header.Add("Access-Control-Allow-Headers", "Content-Type")
```

Which results into the following headers being written  

Accept:[*/*] 
Accept-Encoding:[gzip, deflate, br] 
Accept-Language:[en-GB,en;q=0.9,en-US;q=0.8,fr;q=0.7] 
**Access-Control-Allow-Headers:[Content-Type] 
Access-Control-Allow-Origin:[*] 
Access-Control-Request-Headers:[content-type,x-clientservice-clienttag] 
Access-Control-Request-Method:[GET]** 
Cache-Control:[max-age=0] 
Connection:[keep-alive] 
Sec-Fetch-Dest:[empty] 
**Sec-Fetch-Mode:[cors]** 
Sec-Fetch-Site:[same-site] 
User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36]] 

Any suggestions on how to address this issue ? 

Thanks
Tarun

**Comment by koltyakov** [comment]
Hi @tarundhillon,

[Added CORS support](https://github.com/koltyakov/gosip-sandbox/commit/9ef6a260dc5094667efcf3553c0f6a810f9e6ca6) to the sample. I usually use to route such requests via Local Dev Server proxying to the API URL.

Anyways, please check if it works for you now:

![image](https://user-images.githubusercontent.com/7816483/195335748-13d94609-13f8-4ef8-aecd-6495b9eb5dbd.png)

**Comment by tarundhillon** [comment]
thanks for the adding the function .. I am still getting the options request getting rejected 

![image](https://user-images.githubusercontent.com/2943230/195341686-4b2755f9-5b3d-4860-bc0f-51351260e32a.png)

ps I have added couple of extra headers to the enableCors function
```
(*w).Header().Set("Access-Control-Allow-Origin", "*")
(*w).Header().Set("Access-Control-Allow-Methods", "OPTIONS, HEAD, GET, POST, PUT")
(*w).Header().Set("Access-Control-Allow-Headers", "Content-Type")
```

**Comment by tarundhillon** [comment]
adding the below line did the trick !! 

(*w).Header().Set("Access-Control-Allow-Headers", "*")

Thanks

**Comment by d-tdhillon** [comment]
Hi @koltyakov the default library even though it adds CORS headers

```
func enableCors(w *http.ResponseWriter) {
	(*w).Header().Set("Access-Control-Allow-Origin", "*")
	(*w).Header().Set("Access-Control-Allow-Methods", "OPTIONS, HEAD, GET, POST, PUT")
	(*w).Header().Set("Access-Control-Allow-Headers", "*")
}
```
There is  an issue for requests with OPTION  method which need a 200 response. I have put in a noddy fix like below in the samples/spproxy/main.go to make it work .. but not sure if this is the correct way to handle this request. 

```
	log.Printf("Checking method");
		if r.Method == "OPTIONS"{
			log.Printf("Method :: %s >> %s", r.Method, r.RequestURI)
			w.WriteHeader(200)
			return
		}
```
Let me know if the above works I can try to submit a change.

**Comment by koltyakov** [comment]
Hi @d-tdhillon, thanks! Pushed a change. Please check if it works for you?

**Comment by d-tdhillon** [comment]
@koltyakov it's fixed. works perfectly. thanks
