### ISSUE TITLE
spupload large files are getting dropped

### ISSUE THREAD

**Issue by tarundhillon** [koltyakov/gosip-sandbox#5]
I am trying to upload a local folder to a SharePoint folder seems like large files marked in red are getting dropped without warning. 

![image](https://user-images.githubusercontent.com/2943230/195382595-ff51939e-f8fe-4053-8da6-f196a09abba1.png)

![image](https://user-images.githubusercontent.com/2943230/195383324-8c91d108-9611-4f08-b4cc-655ed44d6d5a.png)

Any work around suggestions ? 

Thanks

**Comment by koltyakov** [comment]
That's interesting. Any ideas how to repro? Is it always large files missed?
I've been uploading frontend assets with even larger artifacts many times and never seen that some files missed, especially without producing any error.

**Comment by tarundhillon** [comment]
Yes its always the largest two files, which are not getting picked up. Did some debugging  

In the upload file function the large files are giving an  access error (very strange because access is work for rest of the files)

```
file, err := files.Add(filepath.Base(filePath), data, true)
	if err != nil {
		log.Printf("Error file.Add %s", err)
		if strings.Contains(err.Error(), "System.IO.DirectoryNotFoundException") || strings.Contains(err.Error(), "Access Denied") {
```

```
2022/10/12 16:52:07 ❌ : /Users/xxxx/Workspace/xxxxce/dist/xxxance/main.9884241f0cb42dff.js: unable to request api: 403 Forbidden :: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

```

[main.9884241f0cb42dff.js.txt](https://github.com/koltyakov/gosip-sandbox/files/9766704/main.9884241f0cb42dff.js.txt)
[196.7266dd2d211a93f4.js.txt](https://github.com/koltyakov/gosip-sandbox/files/9766707/196.7266dd2d211a93f4.js.txt)
9766688/main.9884241f0cb42dff.js.txt)
	
I have attached the faulting js files with .txt

**Comment by koltyakov** [comment]
It's definitely not the size, I was able to upload these and also a few a bit larger.

![image](https://user-images.githubusercontent.com/7816483/195397161-f7d806eb-942d-4ac9-b361-916d60ea6c68.png)

Don't pay attention to the timings, I'm on a potato internet right now.

Maybe, it's a sort of content antivirus checks situation? Can you upload same JS files manually?

**Comment by tarundhillon** [comment]
Hmm very strange .. i am able to upload them manually. Looks like an environment issue, let me investigate a bit more.

**Comment by d-tdhillon** [comment]
In my new setup this is working just fine.. hence closing it.
