### ISSUE TITLE
On-demand chrome window auto-closing with error

### ISSUE THREAD

**Issue by d-tdhillon** [koltyakov/gosip-sandbox#6]
I am setting up my environment on a new mac machine (M1 processor).  I am getting the below  error when I am trying to run spproxy. 

`go run ./samples/spproxy -strategy ondemand -config ./config/private.json`

The chrome window temporarily flashes and closes with the below message in the terminal 

> 2023/03/19 09:38:23 can't request the site, unable to request api: websocket.Dial ws://127.0.0.1:51290/devtools/browser/4a02b57d-72a3-40cd-8d1e-26f71c775dda: bad status
> exit status 1

Any suggestions on what potentially could be the problem ? 

Thanks
Tarun

**Comment by koltyakov** [comment]
Hi @d-tdhillon,

Looks like this https://github.com/zserge/lorca/issues/184

Checking if adding this Chrome flag will help.

**Comment by koltyakov** [comment]
Yep, that was it. Worked for me. https://github.com/koltyakov/gosip-sandbox/commit/8845e13bfa43d3e33e7e15c6d3ce31ef6cbc6a84

**Comment by d-tdhillon** [comment]
Thanks  @koltyakov  ! That worked for me too..
